language: go
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
matrix:
  include:
  - go: 1.9.2
script:
- go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
- go vet $(go list ./... | grep -v vendor)
- go test $(go list ./... | grep -v vendor)
